### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by Gerrit0** [pboyd/cheeseshop#1]
https://github.com/pboyd/cheeseshop/blob/e2f38decf48875f8bdef7555d63c66931902bcde/cheeseshop.cpp#L34-L38

This code has a memory leak if I have a `CheeseShop` which already has a `clerkName` pointer

It'd be better to use a `std::unique_ptr` here, though I get why you didn't given the subject of your post... raw pointers are almost always a bad idea.

**Comment by pboyd** [comment]
Good point, thank you. I'll fix it and update the post (though I won't have a chance for a few days).

-------- Original Message --------

**Comment by pboyd** [comment]
This has been fixed. Thanks again.
